title: "vi-control-asic-sky130"
description: "  "
lang: en

url: "https://samizo-aitl.github.io"
baseurl: "/vi-control-asic-sky130"

# NO THEME â€” custom layout only
theme: null

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
