title: "intersample-supervisory-control"
description: "  "
lang: en

url: "https://samizo-aitl.github.io"
baseurl: "/intersample-supervisory-control"

# NO THEME â€” custom layout only
theme: null

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
